name: fatapp
description: Fatec SCS mobile application

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  barcode_scan: ^1.0.0
  flutter_dotenv: ^2.1.0
  dbcrypt: ^1.0.0
  font_awesome_flutter: ^8.5.0
  dio: ^3.0.7
  cupertino_icons: ^0.1.3
  carousel_slider: ^1.3.1
  fluttertoast: ^3.1.3
  masked_text: ^0.0.6
  smooth_star_rating: ^1.0.3
  validators: ^2.0.0+1
  path_provider: ^1.4.5
  shared_preferences: ^0.5.4+6
  gradient_widgets: ^0.5.0
  intl: ^0.16.0
  connectivity: 0.4.5+7
  flutter_launcher_icons: ^0.7.4
  share: ^0.6.3+3
  cached_network_image: ^1.1.3
  google_maps_flutter: ^0.5.21+12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/images/logo.png

module:
  androidX: true

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - .env

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-RegularItalic.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-BoldItalic.ttf
          style: italic
          weight: 800
    - family: Playfair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 800
    - family: Noto
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 800